name: README build

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 */6 * * *"
    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "warning"
                type: choice
                options:
                    - info
                    - warning
                    - debug
            tags:
                description: "Test scenario tags"
                required: false
                type: boolean
            environment:
                description: "Environment to run tests against"
                type: environment
                required: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout current repository to Master branch
              uses: actions/checkout@v1
            - name: Setup NodeJs 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: Cache dependencies and build outputs to improve workflow execution time.
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
            - name: Install dependencies
              run: npm install
            - name: Generate README file
              run: node index.js
              env:
                  API_KEY: ${{ secrets.API_KEY }}
            - name: Commit and Push new README.md to the repository
              uses: mikeal/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH_NAME: "main"
